name: API ServeRest Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar Newman e HTMLExtra reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Criar pasta para relatórios
        run: mkdir -p relatorios

      - name: Executar testes Newman
        run: |
          npx newman run ServeRest.postman_collection.json \
            -e ServeRest_env.postman_environment.json \
            -r cli,htmlextra \
            --reporter-htmlextra-export relatorios/resultado.html

     # Pendente ajustar a geração do relatório
     # - name: Upload do relatório como artefato
     #  uses: actions/upload-artifact@v3@1fba9b1bff4d4e2f1c83e1d51275d0aa4c3b4c35
     #   with:
      #    name: relatorio-newman
       #   path: relatorios/resultado.html